services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simple-board-frontend
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
      - PORT=5173
